https://habr.com/ru/articles/486358/

In [1]:
import numpy as np
np.random.seed(1000)

Эмбединги 

In [12]:
num_word = 2
num_emb = 4
emb = np.random.randn(num_word,num_emb)
emb

array([[ 0.17793711,  1.39442275,  0.29132019, -0.08200619],
       [ 0.64424261,  0.32807995,  0.85743275, -0.93696928]])

Обучаемые матрицы query, key, value

In [13]:
Q = np.random.rand(num_emb,num_emb)
K = np.random.rand(num_emb,num_emb)
V = np.random.rand(num_emb,num_emb)

Queries

In [14]:
q = emb@Q
q

array([[ 1.37217793,  0.71388711,  1.09149993,  0.71957157],
       [ 0.6860491 ,  0.97000432,  0.82863568, -0.13072229]])

Keys

In [15]:
k = emb@K
k

array([[ 1.15658155,  0.48101366,  1.3682336 ,  1.17343891],
       [-0.00562944,  0.80197415,  1.07285986,  0.12158418]])

Values

In [16]:
v = emb@V
v

array([[0.43614673, 0.57177363, 0.84269036, 1.08145594],
       [0.26316322, 0.74389196, 0.7751859 , 0.68543799]])

Score

In [18]:
from scipy.special import softmax
t = k@q.T
print(t)
s = softmax(t/np.sqrt(num_emb),1)
s

[[4.26822529 2.24042961]
 [1.8233094  1.64717251]]


array([[0.73378227, 0.26621773],
       [0.52200289, 0.47799711]])

Output

In [19]:
z = s@v
z

array([[0.39009545, 0.61759458, 0.82471948, 0.97602894],
       [0.35346111, 0.65404569, 0.81042342, 0.8921605 ]])